# Generated by Django 5.1.1 on 2024-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_matchdataerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(blank=True, null=True)),
                ('season_id', models.IntegerField(blank=True, null=True)),
                ('round_num', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
